### ISSUE TITLE
How to create a custom converter/wrapper for types that would require "--add-exports"?

### ISSUE THREAD

**Issue by michael-schnell** [eclipse-serializer/serializer#151]
I'm currently facing the problem that serializing a [com.google.common.collect.TreeRangeMap](https://guava.dev/releases/20.0/api/docs/com/google/common/collect/TreeRangeMap.html) fails with
`Could not obtain access to "jdk.internal.misc.Unsafe", please start the VM with --add-exports java.base/jdk.internal.misc=ALL-UNNAMED`
Unfortunately I cannot use "--add-exports", so I need a way to circumvent this problem.

Is there a way to have a kind of custom "converter" that allows:
- transforming the "TreeRangeMap" into a standard Java HashMap right **before** Eclipse serialization
- transforming the Java "HashMap" back to the "TreeRangeMap" **after** Eclipse deserialization
So it's like a kind of "wrapper" around the standard serialization/deserialization process.

**Comment by hg-ms** [comment]
Hi
I could not reproduce the access problem using guava 33.3.1-jre, Eclipse Serializer 2.0.0 and Java 23. Instead I got the exception: 
```java
org.eclipse.serializer.persistence.exceptions.PersistenceExceptionTypeNotPersistable: Type not persistable: "class com.google.common.collect.TreeRangeMap$RangeMapEntry".
```

Nevertheless, the access error is most likely caused by the generic type-handlers that try to access private fields of classes to be persisted.
In a fist step it is necessary to identify the affected classes.
To avoid that private access, custom type-handlers are necessary. Such handlers must only use public methods of the affected classes for serialization and deserialization.

**Comment by michael-schnell** [comment]
Is there any example of how to create and register custom type handlers?

**Comment by hg-ms** [comment]
Please have a look at the [Docu](https://docs.eclipsestore.io/manual/storage/customizing/custom-type-handler.html) how to register a custom type-handler, an [example](https://github.com/eclipse-store/store/tree/main/examples/custom-type-handler) and of course already [existing handler implementations](https://github.com/eclipse-serializer/serializer/tree/main/persistence/binary/src/main/java/org/eclipse/serializer/persistence/binary/java).
